# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0027_post_date_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured'),
        ),
    ]
